### PR TITLE
33 add difference function for numeric but  date time cols (yet)

### PR DESCRIPTION
**Pull request by smarks**
the difference method should work for no date and string columns

### CODE REVIEW

**Comment by smarks** [comment]
At least I wanted to push to a PR so we can discuss. Still adding tests.

**Comment by lwhite1** [comment]
I could be wrong, but I don't think your work includes the changes I made
since you branched. Any chance you could pull those? Between that and the
whitespace changes there's a lot to look at and I'm afraid I will overwrite
my own work with a merge.

**Comment by smarks** [comment]
I will straighten this out.

**Comment by smarks** [comment]
I fixed the merge issue. Can you send me  your IDEA settings (I think they are a jar file) so that we use the same whitespace etc.

**Comment by smarks** [comment]
(Also, I am still not getting notified when comments to pull requests are being made - will investigate).

**Comment by lwhite1** [comment]
attached.
i use 2 spaces, like google.

file extension renamed to get past the gmail censors.

**Comment by lwhite1** [comment]
it can be merged, but the whitespace issue still seems present. Is that
what you expect at this point?

If not, you may want to check the files-changed under the pull request

**Comment by smarks** [comment]
If you send me your settings file I'll apply that to this merge and hopefully resolve the whitespace issues

**Comment by lwhite1** [comment]
Sent them yesterday

**Comment by smarks** [comment]
I did not get the settings file. I tried to adjust by hand but it made things worse. I think I should merge this and then get your settings, if that's OK.

**Comment by smarks** [comment]
actually I see more merge conflicts now. I will wait until I get your settings file to proceed with merging from master again.

**Pull request merged**
